### ISSUE TITLE
Dockerize django backend

### ISSUE THREAD

**Issue by sandviklee** [CogitoNTNU/web-backend#22]
Dockerize the Cogito backend to further help the development of projects and the backend itself. 

**Acceptance Criterias**:
- [x] Docker running PostgreSQL server #23 
- [x] Runnable on MacOS
- [x] Runnable on Windows
- [x] Runnable on Linux

**Comment by SverreNystad** [comment]
@sandviklee and I got the docker to run
![image](https://github.com/CogitoNTNU/web-backend/assets/89105607/04f1f445-f952-4f09-be13-fda7284eb22f)

**Comment by SverreNystad** [comment]
This is done, Amazing job @sandviklee
