### ISSUE TITLE
Change endpoint members_by_type to members-by-type

### ISSUE THREAD

**Issue by SverreNystad** [CogitoNTNU/web-backend#38]
I think we should change the endpoint from members_by_type to members-by-type. This is to stay more in line with the rest of the endpoints and common practices. BUT this is destructive as the frontend will not work before changing. I think we should do this after the recruitment period 26.01 is over

**Comment by sandviklee** [comment]
Lets do this simultaniously, when do you have time?

**Comment by SverreNystad** [comment]
This is now done and updated on both back- and frontend.
