### ISSUE TITLE
Update members API to use POST

### ISSUE THREAD

**Issue by sandviklee** [CogitoNTNU/web-backend#6]
Update the API for fetching members of Cogito to POST requests, so it is dynamic and easier to work with in the frontend. 

**Acceptance Criteria**
- [x] Run all tests
- [x] Able to post content to frontend
- [x] Documentation

**Comment by SverreNystad** [comment]
This is documented with swagger, and implemented by @sandviklee in previous commits. I will write some tests and then it will be done.

Note: The magic string"Alle Medlemmer" might be a good case to create a Enum but as I am not certain about the amount of categories and or if they change frequently it might not be the best
