### ISSUE TITLE
Incorrect Role Display for Multiple Category Members

### ISSUE THREAD

**Issue by SverreNystad** [CogitoNTNU/web-backend#62]
@Spiderpig02 has identified a display issue concerning user roles within our system, specifically impacting @sandviklee. As the Chief Marketing Officer (CMO), @sandviklee should be displayed as a member of the 'Styre' category. However, currently, he is only shown under the 'Web' category. This problem appears to stem from the way our system handles categories.

At present, our system is designed to assign users to a single category string, which limits the ability to recognize and display members who belong to multiple categories. This is problematic for individuals like @sandviklee, who hold roles that span across different categories.

**Comment by sandviklee** [comment]
Im on this now!

**Comment by SverreNystad** [comment]
This might be of use:
https://stackoverflow.com/questions/57989562/generating-a-django-model-that-can-have-multiple-values-in-one-field
